apiVersion: v1
kind: Service
metadata:
  name: {{ include "glider.fullname" . }}
  labels:
    {{- include "glider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $.Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }} 
  selector:
    {{- include "glider.selectorLabels" . | nindent 4 }}
