apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glider.fullname" . }}
  labels:
    {{- include "glider.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "glider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "glider.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "glider.fullname" . }}-config
            items:
              - key: glider.conf
                path: glider.conf
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: {{ include "glider.fullname" . }}-tls-secret
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/glider
          {{- if .Values.tls.enabled }}
          - name: tls
            readOnly: true
            mountPath: /etc/glider/tls
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- range $.Values.service.ports }}
          ports:
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
          {{- end }} 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/app/glider"]
          args: ["-config", "/etc/glider/glider.conf"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
